/*
NOTE - There are TWO ways to generate code
1. click search icon and type generate to find the things you want to generate
2. click the 3 lines in the top right hover on 'code' and click 'generate' (4th one down)
 */

public class BasketballPlayer {

    //Fields or Properties (for object)
    private String name;
    private String team;
    private double height;
    private int number;
    private int age;

    //Constructor method
        //Generated by clicking 'Constructor'
    public BasketballPlayer(String name, String team, double height, int number, int age) {
        super(); //Creates the object
        this.name = name; //information coming in (parameters) is set to the field/property
        this.team = team;
        this.height = height;
        this.number = number;
        this.age = age;
    }

    //These are get and set pairs
        //Generated by clicking 'Getters and Setters'
    //Used to allow public access to the fields
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTeam() {
        return team;
    }

    public void setTeam(String team) {
        this.team = team;
    }

    public double getHeight() {
        return height;
    }

    public void setHeight(double height) {
        this.height = height;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    //This method displays a text version of our object on the Console
        //Generated by clicking 'toString()'
    @Override
    public String toString() {
        return "BasketballPlayer{" +
                "name='" + name + '\'' +
                ", team='" + team + '\'' +
                ", height=" + height +
                ", number=" + number +
                ", age=" + age +
                '}';
    }

    //Utility Methods (optional)

}
